name: Continuous Integration (CI)

on:
  push:
    paths:
      - src/**
      - public/**
      - package.json
      - pnpm-lock.yaml
      - astro.config.mjs
      - tailwind.config.cjs
      - tsconfig.json
  workflow_dispatch:

permissions:
  contents: read

jobs:
  launch-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: setup PNPM
        uses: pnpm/action-setup@v6

      - name: Install packages
        run: pnpm install

      - name: Run Astro checks
        run: pnpm check

      - name: Run Linter
        run: pnpm lint:check
